/****** Script para el comando SelectTopNRows de SSMS  ******/
SELECT TOP (1000) [IdCita]
      ,[Fecha]
      ,[HoraInicio]
      ,[HoraFin]
      ,[IdPaciente]
      ,[IdEstadoCita]
      ,[IdAtencion]
      ,[IdMedico]
      ,[IdEspecialidad]
      ,[IdServicio]
      ,[IdProgramacion]
      ,[IdProducto]
      ,[FechaSolicitud]
      ,[HoraSolicitud]
      ,[EsCitaAdicional]
      ,[Observacion]
      ,[CitaDesdeREFCOUNT]
      ,[fechareferencia]
      ,[IdCitaDesde]
      ,[IdEstadoColaCitas]
      ,[HoraUltimoLLamado]
      ,[HoraAtencioninicio]
      ,[HoraAtencionFin]
      ,[HoraLlamadoPac]
      ,[IdEstado]
  FROM [SIGH].[dbo].[Citas] ORDER BY Fecha DESC