/****** Script para el comando SelectTopNRows de SSMS  ******/
SELECT TOP (1000) [IdEmpleado]
      ,[ApellidoPaterno]
      ,[ApellidoMaterno]
      ,[Nombres]
      ,[IdCondicionTrabajo]
      ,[IdTipoEmpleado]
      ,[DNI]
      ,[CodigoPlanilla]
      ,[FechaIngreso]
      ,[FechaAlta]
      ,[Usuario]
      ,[Clave]
      ,[loginEstado]
      ,[loginPC]
      ,[FechaNacimiento]
      ,[idTipoDestacado]
      ,[IdEstablecimientoExterno]
      ,[HisCodigoDigitador]
      ,[ReniecAutorizado]
      ,[idTipoDocumento]
      ,[idSupervisor]
      ,[esActivo]
      ,[IdDepartamento]
      ,[IdServicio_Dep]
  FROM [SIGH].[dbo].[Empleados] WHERE IdEmpleado = 1828