/****** Script para el comando SelectTopNRows de SSMS  ******/
SELECT TOP (1000) [IdCuentaAtencion]
      ,[IdPaciente]
      ,[FechaApertura]
      ,[HoraApertura]
      ,[FechaCierre]
      ,[HoraCierre]
      ,[TotalExonerado]
      ,[TotalAsegurado]
      ,[TotalPagado]
      ,[IdEstado]
      ,[TotalPorPagar]
      ,[IdUsuarioCrea]
      ,[IdUsuarioModifica]
      ,[FechaCreacion]
      ,[FechaModificacion]
      ,[Mensaje]
      ,[idUsuarioMensaje]
  FROM [SIGH].[dbo].[FacturacionCuentasAtencion] order by IdCuentaAtencion desc